# Generated by Django 5.2 on 2025-04-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_weight', models.FloatField()),
                ('quantity', models.FloatField(default='0')),
            ],
            options={
                'db_table': 'dim_asset',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initial_value', models.FloatField()),
            ],
            options={
                'db_table': 'dim_portafolio',
            },
        ),
        migrations.CreateModel(
            name='FactsDailyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'db_table': 'facts_daily_prices',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.portfolio'),
        ),
        migrations.CreateModel(
            name='RawDailyPrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('asset_name', models.CharField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'raw_daily_prices',
                'unique_together': {('date', 'asset_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'portfolio')},
        ),
    ]
