# Generated by Django 5.2 on 2025-04-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_factsdailyprices_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factsdailyprices',
            old_name='weight',
            new_name='asset_value',
        ),
    ]
