# Generated by Django 5.2 on 2025-04-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_weight_factsdailyprices_asset_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactsDailyPricesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('asset_value', models.FloatField()),
                ('snapshot_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'db_table': 'facts_daily_prices_snapshot',
            },
        ),
    ]
