# Generated by Django 5.2 on 2025-04-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_factsdailypricessnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('asset', models.CharField(max_length=40)),
                ('portfolio', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'raw_transactions',
            },
        ),
    ]
